### PR TITLE
Add Apache2 license and notice

### PR DESCRIPTION
**Pull request by amaltaro**
After consulting CMS management, Apache version 2 is the software license we decided to apply.

### CODE REVIEW

**Comment by amaltaro** [comment]
@yuyiguo I just chatted with Eric V. and he said this is the right thing to do. 
We might need to add a header to every single file as well, but I'm still discussing/investigating it and if we do, then we can fix that in the future somehow.

From my side, this is good to go.

**Comment by yuyiguo** [comment]
@amaltaro Does the license require a header to every single file? 
If you think DBS client satisfies CERN's publish requirement, I have no objection to release it to pypi.

**Comment by amaltaro** [comment]
As far as I read, it's not really a requirement but a good practice to avoid any confusion for someone looking at the code. I think we're not adding this header to WMCore at the moment, but if I find an easy tool to automagically add the header, then we might update the files too. I didn't find many comments on this, but this discussion might be worth having a look:
https://forums.dotnetfoundation.org/t/file-headers-and-copyright-statements/1276/8

For the root LICENSE file that is brought in this PR, yes, that's all that we need in terms of software licensing, as discussed with CMS management.

**Comment by yuyiguo** [comment]
Let me know when the code is ready to commit to github.

**Comment by amaltaro** [comment]
This pull request is ready already.

**Comment by yuyiguo** [comment]
I will take a look.

**Comment by yuyiguo** [comment]
@amaltaro Alan, the license file is under DBS. Should it be in DBS/Client?
@goughes Erik, the same question: Should all the client related setup scripts be in DBS/Client in stead of DBS?
Thanks,
Yuyi

**Comment by goughes** [comment]
The license files should be at the root of the repo.  That way if someone clones the repo, they immediately see the license.  When the packages are created for either pycurl-client or dbs-client, the license and notice files are copied from there into the package.  I think the setup files for pypi should also go at the root of the repo, similar to the original setup scripts used for the RPM builds.

**Comment by yuyiguo** [comment]
@amaltaro @goughes 
Alan, Erik  It makes sense to me that the license files and pypi setup files on the the top DBS directory as Erik explained. I'd like to see requirements.dbs_client.txt, requirements.pycurl_client.txt, setup_dbs_client.py and setup_pycurl_client.py in their own directories(client and pycurl client). As soon as these changes made, I will commit them. 
Sorry Erik, I missed your comment on license files.
THanks,
Yuyi

**Comment by amaltaro** [comment]
This PR has nothing to do with the pypi changes you're asking for. This one is simply adding a software license for DBS code. Can you make the same comment/request on the corresponding PR such that Erik can follow up? Thanks

**Comment by yuyiguo** [comment]
Sure, that is not a problem. I will copy and paste my comments.  I made all the comments in this one because these two PRs are related. They need to be both in DBS in order to get DBS build correctly. I will commit them together when they both are ready.

**Pull request merged**
