### PR TITLE
Fixed a migration bug due to exception handling and modernizing  python.

### PR DESCRIPTION
**Pull request by yuyiguo**

### CODE REVIEW

**Comment by ericvaandering** [comment]
I saw your effort report said modernization was done. Were these two types of things the only thing you needed to do?

**Comment by yuyiguo** [comment]
I am confused by your question. What I meant was that I had done all the code upgrade as described by the twiki page.

**Comment by ericvaandering** [comment]
I'm confused because of the 20 or so fixes for 2.7, I only see the exception and the has_key being in this PR. Maybe the rest are ready somewhere or there was nothing to do for the rest?

**Comment by yuyiguo** [comment]
exception and has_key were the major parts. The fixes also included zip, iter.next(), traceback and so on.  They might just a few so not easy to spot.

**Comment by ericvaandering** [comment]
I only looked at the commit names, not the actual changes. Ok. All good then, your job was easy. :-)

**Comment by yuyiguo** [comment]
I see. I grouped them in three batches. It was much easier than I thought. Some of the changes could not merged automatically. That was a bit wired to me.

**Pull request merged**
